header = [
    { title = "About", href="/about" },
    { title = "Attend", href="/attend" }, 
    { title = "Sponsor", href="/sponsor" },
    { title = "Programme", href="/programme" },
    { title = "Register", href = "/register", primary = true }
]
